stages:
  - build

job_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  stage: build
  only:
    - develop
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN hub.githost.io
    - docker build -t hub.githost.io/malinovsky/tolstolutskyi_bookstore_ui:$CI_COMMIT_REF_NAME-${CI_COMMIT_SHA:0:8} .
    - docker push hub.githost.io/malinovsky/tolstolutskyi_bookstore_ui:$CI_COMMIT_REF_NAME-${CI_COMMIT_SHA:0:8}
